### ISSUE TITLE
New bank cannot be read by an EMU ESi-32

### ISSUE THREAD

**Issue by hugovangalen** [dagargo/emu3bm#2]
The header of the bank contains the string "EMU SI-32 v3" which is not understood by the EMU ESi-32 unit that expects "EMULATOR 3X" there.

So then I created an empty bank on the unit itself and retrieved it from the unit. Then, back on Linux, I had overwritten the file `/usr/local/share/emu3bm/empty_bank` and then created a new bank.

After adding the presets, samples and zones, I could then read the resulting file on the unit without any issue. (It does seem that the VCF is configured strange, the Q is at 100% which causes samples to play at a very low volume but that could easily be fixed on the unit itself.)

I have attached the empty bank file to this ticket. Perhaps you could include it.

[empty_bank_emu3x.zip](https://github.com/dagargo/emu3bm/files/5006633/empty_bank_emu3x.zip)

**Comment by dagargo** [comment]
Your bank file look pretty similar to the ESI-2000's one but since I can not test anything on an ESi-32 I assume it's better to just use that bank as a template for creating banks for an ESi-32. Done on 98ce40cdf9727dd4863df80bdfd0519058f2c42c.
Now, it's possible to create banks for a specific device. If no device is set, it's assumed to be an ESI-2000.
```
$ emu3bm -d esi2000 -n bank
$ emu3bm -d emu3x -n bank
```

Regarding the Q issue, there were some comments in the code that were really useful but, again, I can not be sure. The changes applied on fd2491f8f31bed474d68c048e7a5984d3e8ed28e could be enough. Let me know if that works for you.

**Comment by hugovangalen** [comment]
I had not received a notification so I didn't catch your question earlier. I could indeed succesfully create a new bank, that works great now. Thanks!

I have not yet looked at the "Q" value in the latest version, if my day goes according to plan I will be able to check out the latest version after work.

**Comment by dagargo** [comment]
Did you manage to test if the Q values work as intended? Same values should be shown by both emu3bm and the sampler.

**Comment by hugovangalen** [comment]
I am sorry for not getting back earlier on this! I just did a quick test and it appears to work correctly now. 

Thank you!
